name: Fiap2025Producer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build package
      run: npm run build
      env:
        CI: true

    - name: Ensure package directory exists
      run: mkdir -p /home/runner/work/Entrega3/myapp

    - name: Copy build output to package directory
      run: cp -R build/* /home/runner/work/Entrega3/myapp/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to production
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp
        slot-name: Production
        package: /home/runner/work/Entrega3/myapp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}