name: Fiap2025Producer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build Project
      run: |
        dotnet publish -c Release -o /home/runner/work/Entrega3/myapp

    - name: Verify Package
      run: |
        if [ ! -d "/home/runner/work/Entrega3/myapp" ]; then
          echo "Package directory does not exist."
          exit 1
        fi

    - name: Deploy to Production
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp'
        slot-name: 'Production'
        package: '/home/runner/work/Entrega3/myapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}